- name: Configure Cart
  hosts: cart
  become: yes
  tasks:
    - name: Enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create System cart roboshop
      ansible.builtin.cart:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: Delete app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Delete cart Zip File
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent

    - name: Download cart source code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: unarchive cart to app directory
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      community.general.npm:
        path: /app

    - name: Copy cart Service
      ansible.builtin.template:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes
