- name: Configure Shipping server
  hosts: shipping
  become: yes
  tasks:
    - name: Install Maven and MySql
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
      - maven
      - mysql

    - name: Create System User roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop is a system user"

    - name: Delete app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Delete shipping Zip File
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent

    - name: Download shipping source code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: Unarchive shipping to app directory
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: Install maven dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Rename Jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: Create Systemctl Service
      ansible.builtin.template:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Import shipping records
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: "{{ MYSQL_HOST }}"
        login_user: root
        login_password: RoboShop@1
        target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

    - name: Enable and start shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes

